### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.ogsdroid.Board.draw(android.graphics.Canvas, int)' on a null object reference

### ISSUE THREAD

**Issue by nathanj** [nathanj/ogsdroid#11]
USER_COMMENT=null
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'void com.ogsdroid.Board.draw(android.graphics.Canvas, int)' on a null object reference
        at com.ogsdroid.BoardView.onDraw(BoardView.java:104)
        at android.view.View.draw(View.java:15249)
        at android.view.View.updateDisplayListIfDirty(View.java:14185)
        at android.view.View.getDisplayList(View.java:14207)
        at android.view.View.draw(View.java:14977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3200)
        at android.view.View.updateDisplayListIfDirty(View.java:14180)
        at android.view.View.getDisplayList(View.java:14207)
        at android.view.View.draw(View.java:14977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
        at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1195)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3200)
        at android.view.View.draw(View.java:15252)
        at android.view.View.updateDisplayListIfDirty(View.java:14185)
        at android.view.View.getDisplayList(View.java:14207)
        at android.view.View.draw(View.java:14977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3200)
        at android.view.View.updateDisplayListIfDirty(View.java:14180)
        at android.view.View.getDisplayList(View.java:14207)
        at android.view.View.draw(View.java:14977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3200)
        at android.view.View.updateDisplayListIfDirty(View.java:14180)
        at android.view.View.getDisplayList(View.java:14207)
        at android.view.View.draw(View.java:14977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3200)
        at android.view.View.updateDisplayListIfDirty(View.java:14180)
        at android.view.View.getDisplayList(View.java:14207)
        at android.view.View.draw(View.java:14977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3200)
        at android.view.View.updateDisplayListIfDirty(View.java:14180)
        at android.view.View.getDisplayList(View.java:14207)
        at android.view.View.draw(View.java:14977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3200)
        at android.view.View.draw(View.java:15252)
        at android.widget.FrameLayout.draw(FrameLayout.java:598)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2650)
        at android.view.View.updateDisplayListIfDirty(View.java:14185)
        at android.view.View.getDisplayList(View.java:14207)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2560)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2382)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2012)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1084)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5990)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
        at android.view.Choreographer.doFrame(Choreographer.java:550)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5343)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

CUSTOM_DATA=
PHONE_MODEL=XT1032
BRAND=motorola
ANDROID_VERSION=5.1
APP_VERSION_NAME=0.9.1

**Comment by nreusse** [comment]
Hi, i think it was me who sent this report. I created a game from the app, but i could not place a stone (this is an unrelated issue). So i played and finished the game in the browser, and when i reopened the app afterwards, it crashed. Hope this helps and thanks for this app! ;)

**Comment by nathanj** [comment]
Thanks for the info. It sounds like it should be easy to reproduce.

The issue of not being able to place a stone is something that I have noticed before but have not been able to track down. My guess is the game connection was closed/reset for some reason. Usually going back and re-entering the game will fix it.
